spring:
  application:
      name: redis-lettuce

security.ignored: /**
spring.security.enabled: false
management.security.enabled: false
security.basic.enabled: false

server:
  contextPath: /redis-lettuce
  port: 8002

redis:
  database: 5
  password:
  sentinel:
    master: redis-cluster # Default
    nodes:

